[versions]

androidCompileSdk = "34"
androidMinSdk = "21"
androidTargetSdk = "34"

androidGradlePlugin = "8.1.4"
kotlin = "1.9.21"

[libraries]

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"

google-gson = "com.google.code.gson:gson:2.10.1"
tencent-mmkv = "com.tencent:mmkv:1.3.2"

squareup-moshi = "com.squareup.moshi:moshi-kotlin:1.14.0"
sd-closeable = "com.github.zj565061763:closeable:1.0.0-beta06"

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
